stages:
  process:
    cmd: python src/preprocess.py --dimrec 1
    deps:
    - src/preprocess.py
    - data/stocks.csv
    outs:
    - data/data_preprocessed.csv
    - data/processed_df.csv
    - plots/timeseries.jpeg
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/data_preprocessed.csv
    - data/processed_df.csv
    outs:
    - plots/cdistribution.jpeg
    - plots/clustered_timeseries.jpeg
    - plots/clusters.jpeg
    metrics:
    - model/metrics.json:
        cache: false
